


export const skillSuggestions = [
  // 🔹 Technical / IT Skills
  { id: "JavaScript", text: "JavaScript" },
  { id: "React", text: "React" },
  { id: "Node.js", text: "Node.js" },
  { id: "Express", text: "Express" },
  { id: "MongoDB", text: "MongoDB" },
  { id: "HTML", text: "HTML" },
  { id: "CSS", text: "CSS" },
  { id: "Redux", text: "Redux" },
  { id: "TypeScript", text: "TypeScript" },
  { id: "Next.js", text: "Next.js" },
  { id: "Python", text: "Python" },
  { id: "Django", text: "Django" },
  { id: "Java", text: "Java" },
  { id: "Spring Boot", text: "Spring Boot" },
  { id: "C++", text: "C++" },
  { id: "SQL", text: "SQL" },
  { id: "PostgreSQL", text: "PostgreSQL" },
  { id: "MySQL", text: "MySQL" },
  { id: "Git", text: "Git" },
  { id: "Docker", text: "Docker" },
  { id: "Kubernetes", text: "Kubernetes" },
  { id: "AWS", text: "AWS" },
  { id: "Azure", text: "Azure" },
  { id: "Firebase", text: "Firebase" },
  { id: "REST API", text: "REST API" },
  { id: "GraphQL", text: "GraphQL" },
  { id: "Testing", text: "Testing" },
  { id: "Jest", text: "Jest" },
  { id: "Cypress", text: "Cypress" },
  { id: "Agile", text: "Agile" },
  { id: "DevOps", text: "DevOps" },

  // 🔹 General Office / Corporate Skills
  { id: "MS Office", text: "MS Office" },
  { id: "Excel", text: "Excel" },
  { id: "Data Entry", text: "Data Entry" },
  { id: "Customer Service", text: "Customer Service" },
  { id: "Sales", text: "Sales" },
  { id: "Marketing", text: "Marketing" },
  { id: "Digital Marketing", text: "Digital Marketing" },
  { id: "SEO", text: "SEO" },
  { id: "Content Writing", text: "Content Writing" },
  { id: "Graphic Design", text: "Graphic Design" },
  { id: "Accounting", text: "Accounting" },
  { id: "Bookkeeping", text: "Bookkeeping" },
  { id: "Project Management", text: "Project Management" },
  { id: "Supply Chain", text: "Supply Chain" },
  { id: "HR Management", text: "HR Management" },
  { id: "Recruitment", text: "Recruitment" },

  // 🔹 Healthcare Skills
  { id: "Nursing", text: "Nursing" },
  { id: "Patient Care", text: "Patient Care" },
  { id: "First Aid", text: "First Aid" },
  { id: "Medical Coding", text: "Medical Coding" },
  { id: "Pharmacy", text: "Pharmacy" },
  { id: "Lab Technician", text: "Lab Technician" },

  // 🔹 Education & Training
  { id: "Teaching", text: "Teaching" },
  { id: "Classroom Management", text: "Classroom Management" },
  { id: "Curriculum Development", text: "Curriculum Development" },
  { id: "Online Tutoring", text: "Online Tutoring" },
  { id: "Public Speaking", text: "Public Speaking" },

  // 🔹 Trades & Other Jobs
  { id: "Driving", text: "Driving" },
  { id: "Electrician", text: "Electrician" },
  { id: "Plumbing", text: "Plumbing" },
  { id: "Carpentry", text: "Carpentry" },
  { id: "Welding", text: "Welding" },
  { id: "Mechanic", text: "Mechanic" },
  { id: "Cooking", text: "Cooking" },
  { id: "Housekeeping", text: "Housekeeping" },
  { id: "Security", text: "Security" },

  // 🔹 Soft Skills
  { id: "Communication", text: "Communication" },
  { id: "Presentation", text: "Presentation" },
  { id: "Problem Solving", text: "Problem Solving" },
  { id: "Teamwork", text: "Teamwork" },
  { id: "Leadership", text: "Leadership" },
  { id: "Time Management", text: "Time Management" },
  { id: "Creativity", text: "Creativity" },
  { id: "Critical Thinking", text: "Critical Thinking" },
  { id: "Adaptability", text: "Adaptability" },
  { id: "Negotiation", text: "Negotiation" },
  { id: "Collaboration", text: "Collaboration" },
  { id: "Decision Making", text: "Decision Making" },
  { id: "Attention to Detail", text: "Attention to Detail" },
  { id: "Active Listening", text: "Active Listening" },
  { id: "Interpersonal Skills", text: "Interpersonal Skills" },
];
